app <- ShinyDriver$new("../../")
app$snapshotInit("3L_all")

app$setInputs(Score = "EQ-5D-3L")
app$uploadFile(file1 = "3L.csv")
app$setInputs(col1 = "MO")
app$setInputs(col2 = "SC")
app$setInputs(col3 = "U")
app$setInputs(col3 = "UA")
app$setInputs(col4 = "PA")
app$setInputs(col5 = "A")
app$setInputs(col5 = "AD")
app$setInputs(Country = "Europe")
app$setInputs(ShowDataButton = "click")
app$setInputs(goButton = "click")
app$snapshot()
app$setInputs(multiple = "Info")
app$snapshot()
app$setInputs(multiple = "Summary")
app$snapshot()
app$setInputs(multiple = "Plot")
app$snapshot()
app$setInputs(multiple = "Index values")
app$snapshot()
