app <- ShinyDriver$new("../../")
app$snapshotInit("3L_error")

app$setInputs(Score = "EQ-5D-3L")
app$setInputs(type = "Single")
app$setInputs(col1 = "1")
app$setInputs(col2 = "2")
app$setInputs(col3 = "3")
app$setInputs(col4 = "4")
app$setInputs(col5 = "1")
app$setInputs(Method = "VAS")
app$setInputs(Country = "Finland")
app$setInputs(Country = "France")
app$setInputs(ShowDataButton = "click")
app$setInputs(single = "Result")
app$setInputs(goButton = "click")
app$setInputs(single = "Input score")
app$snapshot()
app$setInputs(single = "Result")
app$snapshot()
