app <- ShinyDriver$new("../../")
app$snapshotInit("3L_single")

app$setInputs(Score = "EQ-5D-3L")
app$setInputs(type = "Single")
app$setInputs(col1 = "1")
app$setInputs(col2 = "1")
app$setInputs(col3 = "2")
app$setInputs(col4 = "2")
app$setInputs(col5 = "2")
app$setInputs(ShowDataButton = "click")
app$setInputs(goButton = "click")
app$snapshot()
app$setInputs(single = "Result")
app$snapshot()
