app <- ShinyDriver$new("../../")
app$snapshotInit("5L-errorcol")

app$uploadFile(file1 = "5L.csv")
app$setInputs(col1 = "mo")
app$setInputs(col2 = "sc")
app$setInputs(col3 = "UA")
app$setInputs(col4 = "PA")
app$setInputs(col5 = "AD")
app$setInputs(ShowDataButton = "click")
app$setInputs(goButton = "click")
app$setInputs(multiple = "Info")
app$snapshot()
app$setInputs(multiple = "Summary")
app$snapshot()
app$setInputs(multiple = "Plot")
app$snapshot()
app$setInputs(multiple = "Index values")
app$snapshot()
