app <- ShinyDriver$new("../../")
app$snapshotInit("5L_single")

app$setInputs(type = "Single")
app$setInputs(col1 = "1")
app$setInputs(col2 = "1")
app$setInputs(col3 = "1")
app$setInputs(col4 = "1")
app$setInputs(col5 = "1")
app$setInputs(Country = "England")
app$setInputs(ShowDataButton = "click")
app$setInputs(goButton = "click")
app$snapshot()
app$setInputs(single = "Result")
app$snapshot()
